# Generated by Django 3.1.7 on 2021-03-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(default='', max_length=100)),
                ('cpu_usage', models.IntegerField()),
                ('mem_usage', models.IntegerField()),
            ],
        ),
    ]
